server:
  port:  8008

spring:
  datasource:
      url: jdbc:hsqldb:mem:tdd
      username: sa
      password:
      driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
